import _JSXStyle from "../styled-jsx.es.js";
import React from 'react';
import { useRouter } from 'next/router';
import { useTheme } from '@geist-ui/core';
import { isLocaleRTL, getLocaleDirection, getLocaleAlignment } from '../helpers/index.js';
export default function (_ref) {
  var config = _ref.config,
      children = _ref.children;
  var theme = useTheme();

  var _useRouter = useRouter(),
      _useRouter$locale = _useRouter.locale,
      locale = _useRouter$locale === void 0 ? config.defaultLocale : _useRouter$locale;

  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("div", {
    className: _JSXStyle.dynamic([["4085999581", [theme.type == 'light' ? config.theme.lightBackground : config.theme.darkBackground, config.theme.width, theme.layout.pageMargin, theme.type === 'dark' ? config.theme.darkBackground : config.theme.lightBackground, theme.palette.accents_4, theme.palette.code, theme.palette.code, theme.palette.accents_4, theme.palette.accents_4, theme.palette.code, theme.palette.accents_4, theme.palette.code, isLocaleRTL(locale) ? 'end' : 'start', isLocaleRTL(locale) ? 'right' : 'left', getLocaleDirection(locale), isLocaleRTL(locale) && 'absolute !important', isLocaleRTL(locale) && '2.5rem !important', getLocaleDirection(locale), getLocaleAlignment(locale), isLocaleRTL(locale) && '0.6em !important', getLocaleDirection(locale), getLocaleAlignment(locale), isLocaleRTL(locale) && '0.6rem !important']]]) + " " + "PageWrapper"
  }, /*#__PURE__*/React.createElement("div", {
    className: _JSXStyle.dynamic([["4085999581", [theme.type == 'light' ? config.theme.lightBackground : config.theme.darkBackground, config.theme.width, theme.layout.pageMargin, theme.type === 'dark' ? config.theme.darkBackground : config.theme.lightBackground, theme.palette.accents_4, theme.palette.code, theme.palette.code, theme.palette.accents_4, theme.palette.accents_4, theme.palette.code, theme.palette.accents_4, theme.palette.code, isLocaleRTL(locale) ? 'end' : 'start', isLocaleRTL(locale) ? 'right' : 'left', getLocaleDirection(locale), isLocaleRTL(locale) && 'absolute !important', isLocaleRTL(locale) && '2.5rem !important', getLocaleDirection(locale), getLocaleAlignment(locale), isLocaleRTL(locale) && '0.6em !important', getLocaleDirection(locale), getLocaleAlignment(locale), isLocaleRTL(locale) && '0.6rem !important']]]) + " " + "PageContent"
  }, children)), /*#__PURE__*/React.createElement(_JSXStyle, {
    id: "4085999581",
    dynamic: [theme.type == 'light' ? config.theme.lightBackground : config.theme.darkBackground, config.theme.width, theme.layout.pageMargin, theme.type === 'dark' ? config.theme.darkBackground : config.theme.lightBackground, theme.palette.accents_4, theme.palette.code, theme.palette.code, theme.palette.accents_4, theme.palette.accents_4, theme.palette.code, theme.palette.accents_4, theme.palette.code, isLocaleRTL(locale) ? 'end' : 'start', isLocaleRTL(locale) ? 'right' : 'left', getLocaleDirection(locale), isLocaleRTL(locale) && 'absolute !important', isLocaleRTL(locale) && '2.5rem !important', getLocaleDirection(locale), getLocaleAlignment(locale), isLocaleRTL(locale) && '0.6em !important', getLocaleDirection(locale), getLocaleAlignment(locale), isLocaleRTL(locale) && '0.6rem !important']
  }, "@font-face{font-family:'Yekan';src:url('/fonts/Yekan/Yekan.woff');}html,body{background-color:".concat(theme.type == 'light' ? config.theme.lightBackground : config.theme.darkBackground, "!important;}html,body,a,p,small,h1,h2,h3,h4,h5,h6,dd,dt,dl{font-family:'Inter','Yekan','Segoe UI','Roboto' !important;}.PageWrapper{-webkit-transform:translateY(-5px);-ms-transform:translateY(-5px);transform:translateY(-5px);}.PageContent{width:").concat(config.theme.width, ";max-width:100%;margin:0 auto;padding:0 ").concat(theme.layout.pageMargin, ";-webkit-transform:translateY(-35px);-ms-transform:translateY(-35px);transform:translateY(-35px);box-sizing:border-box;}.divider>span{background-color:").concat(theme.type === 'dark' ? config.theme.darkBackground : config.theme.lightBackground, " !important;color:").concat(theme.palette.accents_4, " !important;}.clear-icon>svg{color:").concat(theme.palette.code, " !important;}a{color:").concat(theme.palette.code, " !important;-webkit-transition:color 0.3s ease;transition:color 0.3s ease;}a:hover{color:").concat(theme.palette.accents_4, " !important;}.FooterLink{color:").concat(theme.palette.accents_4, " !important;-webkit-transition:color 0.3s ease;transition:color 0.3s ease;}.FooterLink:hover{color:").concat(theme.palette.code, " !important;}.Bread a{color:").concat(theme.palette.accents_4, " !important;-webkit-transition:color 0.3s ease;transition:color 0.3s ease;}.Bread a:hover{color:").concat(theme.palette.code, " !important;}.Bread>span{white-space:nowrap;}table{overflow:'scroll' !important;}.avanti>.item{-webkit-box-pack:").concat(isLocaleRTL(locale) ? 'end' : 'start', ";-webkit-justify-content:").concat(isLocaleRTL(locale) ? 'end' : 'start', ";-ms-flex-pack:").concat(isLocaleRTL(locale) ? 'end' : 'start', ";justify-content:").concat(isLocaleRTL(locale) ? 'end' : 'start', ";}input::-webkit-input-placeholder{text-align:").concat(isLocaleRTL(locale) ? 'right' : 'left', ";direction:").concat(getLocaleDirection(locale), " !important;}input::-moz-placeholder{text-align:").concat(isLocaleRTL(locale) ? 'right' : 'left', ";direction:").concat(getLocaleDirection(locale), " !important;}input:-ms-input-placeholder{text-align:").concat(isLocaleRTL(locale) ? 'right' : 'left', ";direction:").concat(getLocaleDirection(locale), " !important;}input::placeholder{text-align:").concat(isLocaleRTL(locale) ? 'right' : 'left', ";direction:").concat(getLocaleDirection(locale), " !important;}.collapse>.view>.title>h3{position:").concat(isLocaleRTL(locale) && 'absolute !important', ";right:").concat(isLocaleRTL(locale) && '2.5rem !important', ";direction:").concat(getLocaleDirection(locale), ";text-align:").concat(getLocaleAlignment(locale), ";}.collapse>.view{margin-bottom:").concat(isLocaleRTL(locale) && '0.6em !important', ";}.collapse>.view>.subtitle{direction:").concat(getLocaleDirection(locale), ";text-align:").concat(getLocaleAlignment(locale), ";margin-top:").concat(isLocaleRTL(locale) && '0.6rem !important', ";}")));
}